### ISSUE TITLE
No Backend Service

### ISSUE THREAD

**Issue by NoureddineRmila** [KrisDaCoder/github-graphql-api-app#1]
Can you update the full code of the project? I can't make it works without the backend is showing errors

**Comment by KrisDaCoder** [comment]
There is no backend in this application. I am not persisting any data in the server. The error you are receiving is related to the fact that the token for accessing the GitHub v4 API is invalid. So in order to make the application work yourself you must generate an access token. Go to the developer settings on GitHub for generating a token and replace the GITHUB_BEARER_TOKEN on the environment variables. The application after should not show any errors.
